ALTER TABLE track_features_norm
  ADD COLUMN IF NOT EXISTS mfcc_var DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS key_strength DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS onset_rate DOUBLE PRECISION;
